const { execSync } = require('child_process');
const { writeFileSync } = require('fs');
const { join } = require('path');

function getEnvHash() {
  // Prefer common CI env vars if set. Also allow VITE_COMMIT_HASH to be passed from Railway.
  return (
    process.env.VITE_COMMIT_HASH ||
    process.env.COMMIT_HASH ||
    process.env.GITHUB_SHA ||
    process.env.SOURCE_COMMIT ||
    process.env.REVISION ||
    process.env.RAILWAY_GIT_COMMIT ||
    null
  );
}

function getGitHash() {
  try {
    // Attempt to read git if available in build context
    const hash = execSync('git rev-parse HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
    return hash || null;
  } catch (e) {
    return null;
  }
}

function writeBuildInfo(hash) {
  const target = join(__dirname, '..', 'src', 'buildInfo.js');
  const safe = hash || 'unknown';
  const content = `// This file is autogenerated at build time\nexport const COMMIT_HASH = '${safe}';\n`;
  writeFileSync(target, content, 'utf8');
  console.log('Wrote buildInfo with hash', safe);
}

(function main() {
  const fromEnv = getEnvHash();
  if (fromEnv) {
    console.log('Using commit hash from env var');
    writeBuildInfo(fromEnv);
    return;
  }

  const fromGit = getGitHash();
  if (fromGit) {
    console.log('Using commit hash from git');
    writeBuildInfo(fromGit);
    return;
  }

  console.log('No commit hash available from env or git; writing unknown');
  writeBuildInfo(null);
})();
