const { execSync } = require('child_process');
const { writeFileSync } = require('fs');
const { join } = require('path');

function getGitHash() {
  try {
    const hash = execSync('git rev-parse HEAD').toString().trim();
    return hash;
  } catch (e) {
    return 'unknown';
  }
}

function writeBuildInfo(hash) {
  const target = join(__dirname, '..', 'src', 'buildInfo.js');
  const content = `// This file is autogenerated at build time\nexport const COMMIT_HASH = '${hash}';\n`;
  writeFileSync(target, content, 'utf8');
  console.log('Wrote buildInfo with hash', hash);
}

const hash = getGitHash();
writeBuildInfo(hash);
